import Head from "next/head";

import Layout from "./layout";

export default function Home() {
  return (
    <div className="main h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/logo.svg" />
      </Head>
      <main>
        <Layout>
          <h1>hello</h1>
        </Layout>
      </main>
    </div>
  );
}
